---
name: cmpsc-100-fall-2018-practical6
break: true
indent: 4
---
# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"
src/main:
    java:
        practicalsix/YearCheckerMain.java:
            --single 9 --language Java --exact
            --multi 3 --language Java --exact
            --fragment "println(" --count 4
            --fragment "getHumanReadableAnswer" --count 4
            --fragment "TODO" --count 0 --exact
src/main:
    java:
        practicalsix/YearChecker.java:
            --single 3 --language Java --exact
            --multi 6 --language Java --exact
            --fragment "println(" --count 0
            --fragment "TODO" --count 0 --exact
# --> check the number of commits beyond a threshold
--commits 13
# --> check that the program executes and produces 4 lines of output
# --> check that the output contains a fragment
--command "gradle -q --console plain run" --executes
--command "gradle -q --console plain run" --count 7 --exact
--command "gradle -q --console plain run" --fragment "1452" --count 4 --exact
--command "gradle -q --console plain run" --fragment "Yes" --count 3 --exact
